//MIDI CC control numbers
//These broadly follow standard CC assignments
#define CCmodWheelinput  1 //pitch LFO amount - less from mod wheel
#define CCmasterVolume   7

#define CCleadMix 2
#define CCpolyMix  3
#define CCstringMix  4
#define CCbassMix 5
#define CClfoDelay  6
#define CCpolyPWM 8
#define CCpolyPW 9
#define CClfoSync  10  

#define CCshSource  12
#define CCportVCO2 13
#define CCstringOctave  14
#define CCbassOctave  15
#define CChpfCutoff1  16
#define CClfoSpeed 17
#define CCleadPW  18
#define CCleadPWM 19
#define CCbassPitch  20
#define CCstringPitch  21
#define CCpolyPitch  22
#define CCpolyVCF 23
#define CCleadPitch 24
#define CCleadVCF 25
#define CCpolyDepth  26
#define CCleadDepth  27
#define CCebassDecay 28
#define CCebassRes 29
#define CCstringBassVolume 30
#define CClowEQ 31

#define CCstringAttack 33
#define CCstringRelease 34
#define CCmodSourcePhaser 35
#define CCphaserSpeed 36
#define CCphaserRes  37
#define CCchorusFlange  38
#define CCchorusSpeed 39
#define CCchorusDepth  40
#define CCchorusRes 41
#define CCechoSync 42
#define CCpolyLFOPitch  43
#define CCpolyLFOVCF  44
#define CCpolyVCFRes 45
#define CCpolyVCFCutoff  46
#define CCpolyADSRDepth  47
#define CCpolyAttack  48
#define CCpolyDecay 49
#define CCpolySustain  50
#define CCpolyRelease 51
#define CCechoTime  52
#define CCechoRegen  53
#define CCechoDamp  54
#define CCechoLevel 55
#define CCreverbType 56
#define CCreverbDecay 57
#define CCreverbDamp  58
#define CCreverbLevel  59
#define CCarpSync 60
#define CCarpSpeed 61
#define CCarpRange 62
#define CCebass16 63

#define CCleadPWMmod 65
#define CCleadVCFmod 66
#define CClead2ndVoice 67
#define CCportVCO1  68
#define CCleadLFOPitch  69
#define CCvco1Range  70
#define CCvco2Range 71
#define CCvco2Tune 72
#define CCvco2Volume 73
#define CCEnvtoVCF 74
#define CCleadVCFCutoff  75
#define CCleadVCFRes  76
#define CCleadAttack  77
#define CCleadDecay  78
#define CCleadSustain  79
#define CCleadRelease 80
#define CCmasterTune 81
#define CCleadNPlow  82
#define CCleadNPhigh 83
#define CCleadNPlast 84
#define CCleadNoteTrigger 85
#define CCvco2KBDTrk 86
#define CCleadTrill 87
#define CCleadVCO1wave 88
#define CCleadVCO2wave 89
#define CCpolyWave 90
#define CCpolyPWMSW 91
#define CCLFOTri 92
#define CCLFOSawUp 93
#define CCLFOSawDown 94
#define CCLFOSquare 95
#define CCLFOSH 96
#define CCstrings8 97
#define CCstrings4 98
#define CCpolyNoteTrigger 99
#define CCpolyVelAmp 100
#define CCpolyDrift 101
#define CCpoly16 102
#define CCpoly8 103
#define CCpoly4 104
#define CCbassNoteTrigger 105
#define CCstringbass16 106
#define CCstringbass8 107
#define CChollowWave 108
#define CCbassPitchSW 109
#define CCstringsPitchSW 110
#define CCpolyPitchSW 111
#define CCpolyVCFSW 112
#define CCleadPitchSW 113
#define CCleadVCFSW 114
#define CCpolyAfterSW 115
#define CCleadAfterSW 116
#define CCphaserBassSW 117
#define CCphaserStringsSW 118
#define CCphaserPolySW 119
#define CChighEQ 120
#define CCmodWheel 127
#define CCebass8 122

#define CCallnotesoff 123//Panic button

#define CCpolyLearn 128
#define CCtrillUp 129
#define CCtrillDown 130
#define CCleadLearn 131
#define CCbassLearn 132
#define CCstringsLearn 133
#define CCphaserLeadSW 134
#define CCchorusBassSW 135
#define CCchorusStringsSW 136
#define CCchorusPolySW 137
#define CCchorusLeadSW 138
#define CCechoBassSW 139
#define CCechoStringsSW 140
#define CCechoPolySW 141
#define CCechoLeadSW 142
#define CCreverbBassSW 143
#define CCreverbStringsSW 144
#define CCreverbPolySW 145
#define CCreverbLeadSW 146

#define CCarpOnSW 147
#define CCarpDownSW 148
#define CCarpUpSW 149
#define CCarpUpDownSW 150
#define CCarpRandomSW 151
#define CCarpHoldSW 152
